### ISSUE TITLE
Use `readline` for login

### ISSUE THREAD

**Issue by Yonle** [wh0/snail-cli#14]
I had a suggestion to make `snail auth send-email` as `snail auth login` or `snail auth signin` by using [Readline](https://nodejs.org/api/readline.html).

Here's how it should be done:

```js
const readline = require("readline");
const rl = readline.createInterface(process.stdin, process.stdout);

// Write some code that send to glitch endpoint to generate magic code
// Then, We ask the code
rl.question("Enter your verification code: ", code => {
  // `code` is string
});
```

So when we do `snail auth login`:
```
user@localhost ~:$ snail auth login user@example.com
Enter your verification code: blue-pacific-ocean
Logged as @user!
```

Or when we do not provide email:
```
user@localhost ~:$ snail auth login
Enter your email: user@example.com
Enter your verification code: blue-pacific-ocean
Logged as @user!
```

Referenced at: https://nodejs.org/api/readline.html#readline_rl_question_query_options_callback

**Comment by wh0** [comment]
good timing on suggesting this. I have just added some readline-related code for logging in via password.

but now we're in this weird state where the email code sign in is done with two separate commands but the password sign in has interactive prompts 🤔 

I could make the current `auth send-email` and `auth code` commands ask if no argument is provided, and that'll be nice and consistent with the new `auth password` command. it'll also be nice in general so that you don't have to put your email address and a one-time code into your shell history.

I'm not sure that adding a new separate command to do both steps is the design I want to go with though. I'm thinking about adding a flag to the `send-email` step to have it also prompt for the code.

**Comment by Yonle** [comment]
C'mon, Just keep the command :^)
*🤫Who knows that somebody will need it*

**Comment by wh0** [comment]
added in v2.6.0
